(() => {
  const liveBtn = document.getElementById('liveBtn');
  const liveLabel = document.getElementById('liveLabel');
  const preview = document.getElementById('preview');
  const actionRegistry = new Map();
  const pendingActions = new Map();
  let liveState = 'stopped';
  let actionSeq = 0;
  const setState = (state, message) => { liveState = state; liveBtn?.classList.toggle('active', state === 'ready'); liveBtn?.classList.toggle('connecting', state === 'connecting'); if (liveLabel) liveLabel.textContent = state === 'ready' ? 'Listening' : state === 'connecting' ? 'Connecting' : 'Live'; if (message && window.showToast) window.showToast(message, state === 'error'); };
  const app = () => window.getActiveApp?.();
  const context = () => { const current = app(); return JSON.stringify({ app: current ? { id: current.id, name: current.name, summary: current.summary } : null, actions: current ? (actionRegistry.get(current.id) || []) : [] }); };
  liveBtn?.addEventListener('click', () => { if (!window.CrewNative?.startGeminiLive) return window.showToast?.('Live requires the Android app', true); if (liveState === 'ready' || liveState === 'connecting') { window.CrewNative.stopGeminiLive(); setState('stopped'); return; } if (!window.CrewAI?.hasApiKey?.()) return window.openSettings?.(); setState('connecting'); window.CrewNative.startGeminiLive(context()); });
  window.addEventListener('message', (event) => { if (event.source !== preview?.contentWindow) return; const msg = event.data || {}; if (!msg.__crewLive) return; const current = app(); if (!current || msg.appId !== current.id) return; if (msg.type === 'register') actionRegistry.set(current.id, Array.isArray(msg.actions) ? msg.actions : []); if (msg.type === 'result' && pendingActions.has(msg.id)) { const pending = pendingActions.get(msg.id); pendingActions.delete(msg.id); pending(msg); } });
  function executeAction(name, args) { return new Promise((resolve) => { const current = app(); if (!current || !preview?.contentWindow) return resolve({ ok: false, error: 'No active app' }); const id = `live_${Date.now()}_${++actionSeq}`; pendingActions.set(id, (msg) => resolve(msg.error ? { ok: false, error: msg.error } : { ok: true, result: msg.result ?? null })); preview.contentWindow.postMessage({ __crewLive: true, type: 'execute', id, appId: current.id, name, args }, '*'); setTimeout(() => { if (!pendingActions.has(id)) return; pendingActions.delete(id); resolve({ ok: false, error: 'App action timed out' }); }, 5000); }); }
  window.__crewLiveEvent = async (raw) => { let event; try { event = typeof raw === 'string' ? JSON.parse(raw) : raw; } catch (_) { return; } if (event.type === 'state') { setState(event.state, event.message); return; } if (event.type !== 'tool') return; let result = { ok: false, error: 'Unknown tool' }; if (event.name === 'app_action') { let args = {}; try { args = JSON.parse(event.args?.args_json || '{}'); } catch (_) {} result = await executeAction(event.args?.name || '', args); } else if (event.name === 'modify_app') { const request = String(event.args?.request || '').trim(); if (request && window.modifyApp) { window.CrewNative.respondGeminiLive(event.id, event.name, JSON.stringify({ ok: true, status: 'builder_started' })); window.CrewNative.stopGeminiLive(); setState('stopped'); await window.modifyApp(request); return; } } window.CrewNative?.respondGeminiLive?.(event.id, event.name, JSON.stringify(result)); };
  const originalInject = window.injectRuntimeBridge;
  if (typeof originalInject === 'function') {
    window.injectRuntimeBridge = function(html, appId) {
      const output = originalInject(html, appId);
      const liveScript = `<script>(()=>{let customHandler=null;const norm=s=>String(s||'').replace(/\\s+/g,' ').trim();const describe=()=>{const buttons=[...document.querySelectorAll('button,[role="button"]')].map((el,i)=>({index:i,text:norm(el.innerText||el.getAttribute('aria-label')||el.title)})).filter(x=>x.text).slice(0,30);const inputs=[...document.querySelectorAll('input,textarea,select')].map((el,i)=>({index:i,label:norm(el.getAttribute('aria-label')||el.placeholder||el.name||el.id),type:el.type||el.tagName.toLowerCase()})).slice(0,20);parent.postMessage({__crewLive:true,type:'register',appId:${JSON.stringify(appId)},actions:[{name:'click',description:'Click a visible control. args: text or index',buttons},{name:'set_input',description:'Set a visible input. args: label or index, plus value',inputs}]},'*')};window.crew=window.crew||{};window.crew.live={registerActions(actions,onAction){customHandler=typeof onAction==='function'?onAction:customHandler;parent.postMessage({__crewLive:true,type:'register',appId:${JSON.stringify(appId)},actions:Array.isArray(actions)?actions:[]},'*')},onAction(fn){customHandler=fn}};addEventListener('message',async(e)=>{const m=e.data||{};if(!m.__crewLive||m.type!=='execute'||m.appId!==${JSON.stringify(appId)})return;try{let result;if(customHandler)result=await customHandler(m.name,m.args||{});else if(m.name==='click'){const target=norm(m.args?.text);const els=[...document.querySelectorAll('button,[role="button"]')];const el=els.find(x=>target&&norm(x.innerText||x.getAttribute('aria-label')||x.title).toLowerCase().includes(target.toLowerCase()))||els[Number(m.args?.index)];if(!el)throw new Error('Control not found');el.click();result=true;setTimeout(describe,80)}else if(m.name==='set_input'){const els=[...document.querySelectorAll('input,textarea,select')];const target=norm(m.args?.label);const el=els.find(x=>target&&norm(x.getAttribute('aria-label')||x.placeholder||x.name||x.id).toLowerCase().includes(target.toLowerCase()))||els[Number(m.args?.index)];if(!el)throw new Error('Input not found');el.value=String(m.args?.value??'');el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}));result=true}else throw new Error('Unsupported action '+m.name);parent.postMessage({__crewLive:true,type:'result',id:m.id,appId:${JSON.stringify(appId)},result},'*')}catch(err){parent.postMessage({__crewLive:true,type:'result',id:m.id,appId:${JSON.stringify(appId)},error:err?.message||String(err)},'*')}});addEventListener('load',()=>setTimeout(describe,80));setTimeout(describe,120)})();<\/script>`;
      return output.replace(/<\/head>/i, `${liveScript}</head>`);
    };
  }
})();
